"""init

Revision ID: 3c4b74d1a51a
Revises: 
Create Date: 2022-08-08 12:43:55.264792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c4b74d1a51a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_order'))
    )
    op.create_index(op.f('ix_order_user_uuid'), 'order', ['user_uuid'], unique=False)
    op.create_table('order_item',
    sa.Column('order_uuid', postgresql.UUID(), nullable=False),
    sa.Column('product_uuid', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('order_uuid', 'product_uuid', name=op.f('pk_order_item'))
    )
    op.create_table('product',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_product'))
    )
    op.create_table('transaction',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=False),
    sa.Column('virtual_account', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_transaction')),
    sa.UniqueConstraint('payment_method', 'virtual_account', name=op.f('uq_transaction_payment_method_virtual_account'))
    )
    op.create_index(op.f('ix_transaction_user_uuid'), 'transaction', ['user_uuid'], unique=False)
    op.create_table('transaction_cart',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('product_uuid', postgresql.UUID(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('transaction_uuid', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_transaction_cart'))
    )
    op.create_index(op.f('ix_transaction_cart_product_uuid'), 'transaction_cart', ['product_uuid'], unique=False)
    op.create_index(op.f('ix_transaction_cart_user_uuid'), 'transaction_cart', ['user_uuid'], unique=False)
    op.create_table('transaction_payment',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_uuid', postgresql.UUID(), nullable=False),
    sa.Column('payment_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_transaction_payment'))
    )
    op.create_table('user',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('session', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction_payment')
    op.drop_index(op.f('ix_transaction_cart_user_uuid'), table_name='transaction_cart')
    op.drop_index(op.f('ix_transaction_cart_product_uuid'), table_name='transaction_cart')
    op.drop_table('transaction_cart')
    op.drop_index(op.f('ix_transaction_user_uuid'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('product')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_order_user_uuid'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
